server:
  port: 8080

spring:
  application:
    name: musinsa-catalog

  profiles:
    active: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_db
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath*:scripts/schema.sql
      data-locations: classpath*:scripts/data.sql

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true
      path: /h2-console