### GET 카테고리 별 최저가격 브랜드와 상품 가격, 총액을 조회하는 API
GET http://localhost:8080/api/v1/recommendations/lowest-price-products-of-each-category
Content-Type: application/json

### GET 단일 브랜드로 모든 카테고리 상품을 구매할 때 최저가격에 판매하는 브랜드와 카테고리의 상품가격, 총액을 조회하는 API
GET http://localhost:8080/api/v1/recommendations/lowest-price-brand
Content-Type: application/json

### GET 카테고리 이름으로 최저, 최고 가격 브랜드와 상품 가격을 조회하는 API
GET http://localhost:8080/api/v1/recommendations/lowest-price-product-by-category?categoryName=상의
Content-Type: application/json

